### PR TITLE
Four Key Movement

### PR DESCRIPTION
**Pull request by riamittal93**
Done :D

### CODE REVIEW

**Review by charvakk — COMMENTED** [review]
Do we want to allow the snake to turn back? For example, if it's going left, it cannot go right immediately

**Comment by riamittal93** [comment]
Huh? It does turn immediately. That's the whole point of this 4 key system. Whichever key you press, it will directly go to that direction. It might be a little weird cause the head is the pivot. It might look different if the center of the snake's body is the pivot

**Comment by charvakk** [comment]
I meant we should not allow it to go back immediately. It would die when we implement collision with itself

**Comment by riamittal93** [comment]
That depend on how the player plays. The system what we had before was very confusing. I was never able to predict which way it would turn. We need the controls to be easy so that people can focus on the game. Plus when we get the movement working properly it should be able to co-ordinate with the growth of the snake. Right now the whole snake turns direction. That is not what we want.

**Comment by charvakk** [comment]
I'm not complaining about the controls, I feel they should be this way too. I'm just saying we should handle the edge case of the player pressing the right key when the snake is going left. Right now, it allows the player to do this

**Comment by riamittal93** [comment]
Do you need me to make a change in this or are we doing it later??

**Review by charvakk — APPROVED** [review]

**Pull request merged**
